language: php

env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER: max[self]=0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.3

before_install:
  - composer self-update

install: composer update $COMPOSER_FLAGS --prefer-dist

script: vendor/bin/phpunit --coverage-clover=coverage.clover

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - if [ -f coverage.clover ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
